<?php
require_once __DIR__ . '/first_page.views.inc';
use Drupal\node\NodeInterface;

/**
 * @file
 * Primary module hooks for First Page module.
 */

function first_page_theme()
{
  return [
    'first_page' => [
      'variables' => [
        'title' => NULL,
        'content' => NULL,
      ],
      'template' => 'first-page',
    ],

    'my_hello' => [
      'variables' => [
        'siteName' => NULL,
      ],
      'template' => 'my-hello',
    ],
    'nodes_count' =>[
      'variables' => [
        'totalNodes' => 0
      ],
      'template' => 'nodes-count',
    ],

  ];
}

function first_page_node_presave(NodeInterface $node)
{

  if ($node->getType() === 'page') {

    $current_date = new \DateTime();
    $formatted_date = $current_date->format('d.m.Y');
    $current_title = $node->getTitle();

    if (!str_contains($current_title, $formatted_date)) {
      $new_title = $formatted_date . ' — ' . $current_title;
      $node->setTitle($new_title);

    }
  }
}


function first_page_toolbar() {
  $items = [];

  $items['create_page'] = [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#title' => t('Create Page'),
      '#url' => Drupal\Core\Url::fromRoute('node.add', ['node_type' => 'page']),
      '#attributes' => [
        'class' => ['toolbar-icon', 'toolbar-icon-create-page'],
      ],
    ],
    '#weight' => 20,  // Вес для позиции в тулбаре
    '#attached' => [
      'library' => ['first_page/toolbar-styles'],
    ],
  ];

  return $items;
}


/**
 * Implements hook_cron().
 */
function first_page_cron() {
  $queue = \Drupal::queue('node_update_worker');
  $yesterday = time() - 86400;
  $query = \Drupal::entityQuery('node')
    ->condition('changed', $yesterday, '<')
    ->condition('status', 1)
    ->accessCheck(FALSE);

  $nids = $query->execute();

  foreach ($nids as $nid) {
    $queue->createItem(['nid' => $nid]);
  }
}

function first_page_preprocess_views_view(&$variables) {
 // if ($variables['id'] == 'test_exposed_form') {
    $variables['#attached']['library'][] = 'first_page/exposed-autosubmit';
  //}
}


